outfitter_maintitle=Outfitter

outfitter_openws=Atölye sayfasını aç

outfitter_gui_focusdim=İmleç arayüzün dışına çıkınca pencerenin parlaklığını azaltır
outfitter_urlmsg=Tarayıcı URL'yi değiştirmezse, lütfen URL'yi tarayıcı çubuğuna kendiniz yapıştırın.

outfitter_choose_ws=1. Atölye eklentisi seç
outfitter_ws_title=Atölye eklentisinin başlığı
outfitter_review_deps=Bu modelle gönderilen bağımlılıkları incele

outfitter_depinfo=Bu atölye ögesi aşağıdaki bağımlılıkları bildiriyor. Modelinizle birlikte kurulması ve gönderilmesi gerekenleri seçin. Kullanılamayan ögeler seçilemez. Garry's Mod'u yeniden başlatılana kadar, şu anda kurulmuş ögeler kurulu halde kalır.
outfitter_depcontwo=Bağımlılıklar olmadan devam et

outfitter_choose_of=Model seçmek için bu listedeki modellerden birine tıkla
outfitter_title_blacklist=Satır başına yasaklı bir cümle ekleyin.\n Cümlelerden herhangi biriyle eşleşen bir modelin başlığı engellenecektir.
outfitter_on_tip=Birinin modeli engellendiyse veya gösterilmesi gerekiyorsa bunu aç/kapat
outfitter_choosemdl=Model içeren bir atölye eklentisi seçin

outfitter_friendsonly=Sadece arkadaşlarının modellerini yükle
outfitter_friendsonlytip=Arkadaş olmayan biri model seçtiğinde engellenir
outfitter_dldistance=Model indirme mesafesi
outfitter_dldistancetip=Bir modelin indirilmesi için bir oyuncunun ne kadar yakın olması gerektiği
outfitter_distmode=Uzaklık modu: Bir oyuncuya yaklaştığınızda modeli indirmeye başlayın
outfitter_def=Varsayılan
outfitter_sao=Tüm Modelleri Gör
outfitter_noo=Sadece Yakında Olanlar
outfitter_maxdlsize=En Fazla İndirme Boyutu (MB cinsinden)
outfitter_maxdlsizetip=Bu, bir modelin ve seçilen bağımlılıklarının engellenmeden önce ne kadar büyük olabileceğidir
outfitter_allow_wsdeps=Atölye bağımlılıklarına izin ver
outfitter_allow_wsdepstip=Seçilen atölye bağımlılıklarını modelle birlikte kurar
outfitter_guesschands=Elleri kullan
outfitter_guesschandstip=Oyuncu modelleri için eller tahmin edilsin mi

outfitter_uisfx=Arayüz ses efektleri
outfitter_uisfxtip=Arayüz ses efektleri çalınsın mı
outfitter_dimgui=Arayüz pencere parlaklığını kıs
outfitter_dimguitip=İmleç arayüzün dışına çıkınca pencere parlaklığı azalsın mı?
outfitter_outsidews=Atölye harici modellere izin ver
outfitter_outsidewstip=Atölye dışından HTTP indirmelerine izin verir. Potansiyel olarak tehlikeli!!!

outfitter_untrustedurl=Güvenilmeyen URL'lerden model yükle (TEHLİKELİ, IP sızdırabilir!!!)
outfitter_untrustedurltip=Outfitter varsayılan olarak her yerden HTTP indirmelerine izin vermez, ancak yerel denemelere izin verecek şekilde ayarlanabilir

outfitter_debugtip=Hata ayıklama ögelerini konsola yazdırır. Bir şey yanlışsa bunu etkinleştirin ve bugreportta çıktısını verin.
outfitter_unsafe=Tehlikeli
outfitter_removesafetychecks=Bazı model kontrollerini kaldır (yalnızca kendiniz için). Buna hiç gerek olmamalı. Etkinleştirmeye zorlamak için cfg/outfitter_force_unsafe.cfg dosyasını oluşturun (bir uyarı yazdıracaktır).

outfitter_failsafe=Hata Koruma
outfitter_failsafetip=Model uyguladıktan hemen sonra oyun çökmesi tespit edilirse bu işaretlenir.

outfitter_autoblock=Otomatik Kara Liste
outfitter_autoblocktip=Sizi otomatik olarak çökerten modelleri kara listeye alır

outfitter_legacy=Eski: Yerel oyuncu animasyonları için fullupdate kullan
outfitter_legacytip=Daha önce animasyonları düzeltmek için bir fullupdate'e ihtiyacımız vardı. Şimdi farklı bir teknik kullanılıyor.

outfitter_dlnotif=Eski: İndirme bildirimlerini göster
outfitter_dlnotiftip=Atölyeden model indirirken indirme bildirimlerini göster

outfitter_ofitinfocontext=İçerik menüsünde model bilgilerini göster
outfitter_ofitinfocontexttip=İçerik menüsü tuşunu basılı tutarken bir oyuncunun üzerine gelindiğinde model durumunu ve model yolunu gösterir

outfitter_clrmdlblacklist=Onarım: Kara listeyi temizle
outfitter_fixfullupdate=Onarım: Fullupdate
outfitter_fixlplyanim=Onarım: Yerel oyuncu animasyonlarını düzelt

outfitter_thirdptip=Üçüncü kişiyi etkinleştirir/devre dışı bırakır (yüklüyse)
outfitter_bodygroups=Vücut grupları ve görünümler
outfitter_submitfirst=Vücut grubu veya görünüm değiştirmeden önce seçtiğin modeli gönder
outfitter_autoweartip=Bu modeli sunucularda otomatik olarak seç

outfitter_broadcastof=Bu, seçtiğiniz modeli tüm sunucuya yayınlar
outfitter_remoutfit=Bu, bir model seçtiğinizin tüm izlerini ortadan kaldırır

outfitter_slctwsaddon=Lütfen bir atölye eklentisi seçin
outfitter_loadinginfo=Bilgi yükleniyor...
outfitter_badgma=GMA: Bozuk?

outfitter_dermaalertmsg=Tek oyunculudasınız. Outfitter çalışmayabilir.
outfitter_warning=UYARI

outfitter_warnlist=Bu HTTP URL'si izin listesinde değil

outfitter_deps=Bağımlılıklar...
outfitter_titlebl=Engel listesi
outfitter_allownsfw=NSFW'ye izin ver
outfitter_allownsfwtip=NSFW olan eklentilere izin ver

outfitter_depscho=Bağımlılıkları incelemeden önce bir model seçin
outfitter_depscheck=Atölye bağımlılıkları kontrol ediliyor...

# Credits
outfitter_credits_list=Son olarak, bu karmaşadan sorumlu kişiler bunlarla sınırlı olmamak kaydıyla aşağıdakileri içerir:
outfitter_credits_willox=Outfitter yapmak için araçlarını bize veren eski Facepunch çalışanı
outfitter_credits_capsadmin=Oyuncu Görünüm Özelleştiricisinden (PAC3) ilham alındı
outfitter_credits_aerthas=İlk outfitter prototipi oluşturma konusunda yardım
outfitter_credits_henke=Animasyon düzeltme alternatifi buldu
outfitter_credits_facepunchforum=Facepunch forumları
outfitter_credits_facepunch=LUA ile alakalı özverili bir şekilde yardım etti ve aynı zamanda hepimiz için yıllar boyunca duygusal destek sağladı. Onsuz pek çok şey mümkün olmazdı!
outfitter_credits_garry=<Garry :D> Siz çılgınsınız naptınız lan
outfitter_credits_python1320=Bu çılgınlığı yazan adam
outfitter_credits_metaconstruct=Outfitter'ı mümkün kılan yazılımcı topluluğu
outfitter_credits_ilker=Bağımlılık kurulumunu ayarladı
outfitter_credits_toraichi=Yerelleştirme desteği ekledi
outfitter_credits_you=Outfitterla ilgilendiğin için!

outfitter_about=Outfitter (Hakkında)
outfitter_bout=Hakkımızda
outfitter_desc=Merhaba! Outfitter GMod topluluğunun ihtiyacını karşılamak için yapıldı.\nOutfitter çoğu zaman düzgün çalışmasına rağmen hala hataları olabilir. Hataları bildirerek bu konuda yardımcı olabilirsiniz.
outfitter_close=Kapat
outfitter_bugreport=Hata bildirme
outfitter_getof=Outfitter'ı indir

outfitter_editanyway=Yine de düzenle
