outfitter_maintitle=Outfitter

outfitter_openws=Open workshop page

outfitter_gui_focusdim=Dim GUI when mouse leaves window
outfitter_urlmsg=If the browser does not change URL please paste the URL yourself in the browser bar from your web browser.

outfitter_choose_ws=1. Choose a workshop addon
outfitter_ws_title=Title of the chosen workshop addon
outfitter_review_deps=Review the dependencies sent with this outfit

outfitter_depinfo=This workshop outfit declares the following dependencies. Select the ones that should be mounted and sent with your outfit. Unavailable items cannot be selected. Already-mounted items remain mounted until Garry's Mod restarts.
outfitter_depcontwo=Continue without dependencies

outfitter_choose_of=Click one of the models on this list to choose as your outfit
outfitter_title_blacklist=Add a banned sentence per line.\n An outfit's title matching any of the sentences will be blocked.
outfitter_on_tip=Toggle this if someone's outfit got blocked or should be showing
outfitter_choosemdl=Choose a workshop addon which contains an outfit

outfitter_friendsonly=Load only outfits of friends
outfitter_friendsonlytip=When non friend wears an outfit it gets blocked
outfitter_dldistance=Outfit download distance
outfitter_dldistancetip=How near does a player have to be for an outfit to download
outfitter_distmode=Distance mode: start downloading outfits when you get near a player
outfitter_def=Default Mode
outfitter_sao=See All Outfits
outfitter_noo=Nearby Outfits Only
outfitter_maxdlsize=Maximum download size (in MB)
outfitter_maxdlsizetip=This is how big an outfit and its selected dependencies can be before being blocked
outfitter_allow_wsdeps=Allow workshop dependencies
outfitter_allow_wsdepstip=Mounts selected workshop dependencies along with outfits
outfitter_guesschands=Use hands
outfitter_guesschandstip=Should we guess hands for the playermodels

outfitter_uisfx=UI sounds
outfitter_uisfxtip=Should we play informational sounds
outfitter_dimgui=Dim GUI
outfitter_dimguitip=When mouse leaves the UI should we dim it?
outfitter_outsidews=Allow outfits from outside workshop
outfitter_outsidewstip=Allow HTTP downloads from outside workshop. Unsafe potentially!!!

outfitter_untrustedurl=Load outfits from untrusted URLs (UNSAFE, may leak IP!!!)
outfitter_untrustedurltip=Outfitter by default does not allow HTTP downloads from everywhere, but can be set to allow them for local testing

outfitter_debugtip=Print debug stuff to console. Enable this if something is wrong and in the bugreport give the log output.
outfitter_unsafe=Unsafe
outfitter_removesafetychecks=Remove some outfit checks (for yourself only). This should not be needed ever. Create cfg/outfitter_force_unsafe.cfg to force enable (will print a warning).

outfitter_failsafe=Failsafe
outfitter_failsafetip=This gets ticked if you were detected to crash right after applying outfit.

outfitter_autoblock=Autoblacklist
outfitter_autoblocktip=Blacklists outfits that crashed you automatically

outfitter_legacy=Legacy: Use fullupdate for local player animations
outfitter_legacytip=Previously we needed a fullupdate to fix animations. Now a different technique is used.

outfitter_dlnotif=Legacy: Show downloading notifications
outfitter_dlnotiftip=Show downloading notifications when downloading models from the workshop

outfitter_ofitinfocontext=Show outfit info in context menu
outfitter_ofitinfocontexttip=Shows outfit status and model path when hovering over a player while holding the context menu key

outfitter_clrmdlblacklist=FIX: Clear models blacklist
outfitter_fixfullupdate=FIX: Fullupdate
outfitter_fixlplyanim=FIX: Local player animations

outfitter_thirdptip=Enables/disable thirdperson (if one is installed)
outfitter_autoweartip=Automatically wear this outfit on servers

outfitter_broadcastof=This broadcasts the outfit you have chosen to the whole server
outfitter_remoutfit=This removes all traces of you wearing an outfit

outfitter_slctwsaddon=Please choose a workshop addon
outfitter_loadinginfo=Loading info...
outfitter_badgma=GMA: Not OK?

outfitter_dermaalertmsg=You are playing singleplayer. Outfitter may not work at all.
outfitter_warning=WARNING

outfitter_warnlist=This HTTP URL is not in allowlist

outfitter_deps=Dependencies...
outfitter_titlebl=Title blocklist
outfitter_allownsfw=Allow NSFW
outfitter_allownsfwtip=Allow NSFW rated addons

outfitter_depscho=Choose a model before reviewing dependencies
outfitter_depscheck=Checking workshop dependencies...

# Credits
outfitter_credits_list=Finally, the people responsible for this mess include but are not limited to:
outfitter_credits_willox=Ex-Facepunch who gave us the tools to make outfitter
outfitter_credits_capsadmin=Insipration from Player Appearance Customizer (PAC3)
outfitter_credits_aerthas=Help with initial outfitter prototyping
outfitter_credits_henke=Found anim fix alternative
outfitter_credits_facepunchforum=Facepunch forums
outfitter_credits_facepunch=For helping with all the LAU selflessly and also for emotional support over the years for all of us. Lots of stuff would not have been possible without!
outfitter_credits_garry=<Garry :D> You guys are crazy WTF
outfitter_credits_python1320=The guy who wrote this madness
outfitter_credits_metaconstruct=The programming community that made outfitter possible
outfitter_credits_ilker=Created dependencies mounting
outfitter_credits_toraichi=Added localization support
outfitter_credits_you=For being interested in outfitter!

outfitter_about=Outfitter (About)
outfitter_bout=About
outfitter_desc=Hello there! Outfitter was made to fill the need of the GMod community and for procrastination.\nAlthough mostly working, outfitter still has bugs and you can help with that by reporting them.
outfitter_close=Close
outfitter_bugreport=Bug reporting
outfitter_getof=Get outfitter

outfitter_editanyway=Edit anyway
